name: gwaslab_3.4.40
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=24.0
  - python=3.9.18
  - jupyter==1.0.0
  - pip:
      - adjusttext==0.8
      - biopython==1.83
      - gtfparse==1.3.0
      - gwaslab==3.4.40
      - liftover==1.1.18
      - matplotlib==3.8.3
      - numpy==1.26.4
      - pandas==2.2.0
      - pyensembl==2.2.3
      - pysam==0.19.1
      - scikit-allel==1.3.7
      - scipy==1.12.0
      - seaborn==0.13.2
      - h5py==3.10.0
